//
//  PhraseSeeder.swift
//  EnglishStudyCard
//
//  Created by Kenichi on R 7/11/01.
//
import SwiftData
import Foundation

enum PhraseSeeder {
    static func seed(into context: ModelContext) {
        let samples: [(String,String,String,String)] = [
            // tag, category, en, ja
            // MARK: - I can〜
                        ("I can〜", "日常", "I can help you.", "手伝えますよ。"),
                        ("I can〜", "日常", "I can cook dinner tonight.", "今夜、夕食を作れますよ。"),
                        ("I can〜", "日常", "I can carry that for you.", "それ持ちましょうか。"),
                        ("I can〜", "日常", "I can get it for you.", "それ取ってきますよ。"),
                        ("I can〜", "日常", "I can clean the room later.", "あとで部屋を掃除できますよ。"),
                        ("I can〜", "仕事", "I can finish it by tomorrow.", "明日までに終わらせられます。"),
                        ("I can〜", "仕事", "I can join the meeting.", "会議に参加できます。"),
                        ("I can〜", "仕事", "I can email the client.", "クライアントにメールできます。"),
                        ("I can〜", "仕事", "I can fix the problem.", "その問題を解決できます。"),
                        ("I can〜", "仕事", "I can take care of that.", "それを引き受けられます。"),
                        ("I can〜", "旅行", "I can book a hotel.", "ホテルを予約できます。"),
                        ("I can〜", "旅行", "I can drive us there.", "そこまで運転できますよ。"),
                        ("I can〜", "旅行", "I can carry your bag.", "荷物を持てますよ。"),
                        ("I can〜", "旅行", "I can ask for directions.", "道を聞いてきます。"),
                        ("I can〜", "旅行", "I can take a photo of you.", "写真を撮ってあげます。"),
                        ("I can〜", "人間関係", "I can listen if you want to talk.", "話したければ聞くよ。"),
                        ("I can〜", "人間関係", "I can support you.", "あなたを支えられます。"),
                        ("I can〜", "人間関係", "I can understand how you feel.", "気持ちは分かります。"),
                        ("I can〜", "人間関係", "I can wait as long as you need.", "必要なだけ待てますよ。"),
                        ("I can〜", "人間関係", "I can forgive you.", "あなたを許せます。"),
                        ("I can〜", "学習", "I can speak English a little.", "少し英語が話せます。"),
                        ("I can〜", "学習", "I can study tonight.", "今夜は勉強できます。"),
                        ("I can〜", "学習", "I can help you with your homework.", "宿題を手伝えますよ。"),
                        ("I can〜", "学習", "I can teach you Japanese.", "日本語を教えられます。"),
                        ("I can〜", "学習", "I can memorize this word.", "この単語を覚えられます。"),
                        ("I can〜", "趣味", "I can play the guitar.", "ギターが弾けます。"),
                        ("I can〜", "趣味", "I can draw pretty well.", "けっこう絵が描けます。"),
                        ("I can〜", "趣味", "I can sing this song.", "この歌が歌えます。"),
                        ("I can〜", "趣味", "I can cook Italian food.", "イタリア料理が作れます。"),
                        ("I can〜", "趣味", "I can take good photos.", "いい写真が撮れます。"),
                     
                      

            // MARK: - Can I〜
                        ("Can I〜", "日常", "Can I help you?", "お手伝いしましょうか？"),
                        ("Can I〜", "日常", "Can I sit here?", "ここに座ってもいいですか？"),
                        ("Can I〜", "日常", "Can I have some water?", "お水をもらえますか？"),
                        ("Can I〜", "日常", "Can I open the window?", "窓を開けてもいいですか？"),
                        ("Can I〜", "日常", "Can I turn off the light?", "電気を消してもいいですか？"),
                        ("Can I〜", "仕事", "Can I take a day off tomorrow?", "明日休んでもいいですか？"),
                        ("Can I〜", "仕事", "Can I leave a little early?", "少し早く帰ってもいいですか？"),
                        ("Can I〜", "仕事", "Can I join the meeting?", "その会議に参加してもいいですか？"),
                        ("Can I〜", "仕事", "Can I see the report?", "その報告書を見てもいいですか？"),
                        ("Can I〜", "仕事", "Can I speak with the manager?", "マネージャーと話してもいいですか？"),
                        ("Can I〜", "買い物", "Can I try this on?", "これ試着してもいいですか？"),
                        ("Can I〜", "買い物", "Can I pay by card?", "カードで払ってもいいですか？"),
                        ("Can I〜", "買い物", "Can I have this to go?", "これを持ち帰りにできますか？"),
                        ("Can I〜", "買い物", "Can I see the menu?", "メニューを見てもいいですか？"),
                        ("Can I〜", "買い物", "Can I get a receipt?", "レシートをもらえますか？"),
                        ("Can I〜", "人間関係", "Can I talk to you for a minute?", "少し話せますか？"),
                        ("Can I〜", "人間関係", "Can I give you a hug?", "ハグしてもいい？"),
                        ("Can I〜", "人間関係", "Can I tell you something?", "ちょっと言ってもいい？"),
                        ("Can I〜", "人間関係", "Can I ask your opinion?", "あなたの意見を聞いてもいい？"),
                        ("Can I〜", "人間関係", "Can I come with you?", "一緒に行ってもいい？"),
                        ("Can I〜", "旅行", "Can I get a map?", "地図をもらえますか？"),
                        ("Can I〜", "旅行", "Can I check in early?", "早めにチェックインできますか？"),
                        ("Can I〜", "旅行", "Can I change my seat?", "席を変えてもいいですか？"),
                        ("Can I〜", "旅行", "Can I take photos here?", "ここで写真を撮ってもいいですか？"),
                        ("Can I〜", "旅行", "Can I use Wi-Fi here?", "ここでWi-Fiを使えますか？"),
                        
            // MARK: - Can you 〜
                        ("Can you〜", "日常", "Can you help me?", "手伝ってくれる？"),
                        ("Can you〜", "日常", "Can you pass me the salt?", "塩を取ってくれる？"),
                        ("Can you〜", "日常", "Can you open the window?", "窓を開けてくれる？"),
                        ("Can you〜", "日常", "Can you turn off the light?", "電気を消してくれる？"),
                        ("Can you〜", "日常", "Can you wait a moment?", "ちょっと待ってくれる？"),
                        ("Can you〜", "仕事", "Can you send me the file?", "そのファイルを送ってもらえますか？"),
                        ("Can you〜", "仕事", "Can you join the meeting at 3?", "3時の会議に参加できますか？"),
                        ("Can you〜", "仕事", "Can you check this document?", "この書類を確認してもらえますか？"),
                        ("Can you〜", "仕事", "Can you call the client?", "クライアントに電話してもらえますか？"),
                        ("Can you〜", "仕事", "Can you finish this today?", "これ今日中に終わらせてもらえますか？"),
                        ("Can you〜", "買い物", "Can you give me a receipt?", "レシートをください。"),
                        ("Can you〜", "買い物", "Can you wrap this, please?", "これを包んでもらえますか？"),
                        ("Can you〜", "買い物", "Can you show me a bigger size?", "もっと大きいサイズを見せてもらえますか？"),
                        ("Can you〜", "買い物", "Can you check the price?", "値段を確認してもらえますか？"),
                        ("Can you〜", "買い物", "Can you call a taxi for me?", "タクシーを呼んでもらえますか？"),
                        ("Can you〜", "旅行", "Can you take a picture of me?", "写真を撮ってくれますか？"),
                        ("Can you〜", "旅行", "Can you show me the way?", "道を教えてくれますか？"),
                        ("Can you〜", "旅行", "Can you carry my bag?", "カバンを持ってくれますか？"),
                        ("Can you〜", "旅行", "Can you speak Japanese?", "日本語を話せますか？"),
                        ("Can you〜", "旅行", "Can you wait here?", "ここで待っててくれる？"),
                        ("Can you〜", "人間関係", "Can you be honest with me?", "正直に話してくれる？"),
                        ("Can you〜", "人間関係", "Can you tell me the truth?", "本当のことを教えてくれる？"),
                        ("Can you〜", "人間関係", "Can you forgive me?", "許してくれる？"),
                        ("Can you〜", "人間関係", "Can you give me some advice?", "アドバイスもらえる？"),
                        ("Can you〜", "人間関係", "Can you listen to me?", "話を聞いてくれる？"),
                        
            // MARK: - I got to ~
                        ("I was able to〜", "日常", "I was able to wake up early.", "早起きできました。"),
                        ("I was able to〜", "日常", "I was able to catch the bus.", "バスに間に合いました。"),
                        ("I was able to〜", "日常", "I was able to cook dinner.", "夕飯を作ることができました。"),
                        ("I was able to〜", "日常", "I was able to clean my room.", "部屋を掃除できました。"),
                        ("I was able to〜", "日常", "I was able to finish everything on time.", "全部時間通りに終えることができました。"),
                        ("I was able to〜", "仕事", "I was able to complete the project.", "プロジェクトを完了できました。"),
                        ("I was able to〜", "仕事", "I was able to fix the issue.", "問題を解決できました。"),
                        ("I was able to〜", "仕事", "I was able to join the meeting on time.", "会議に時間通り参加できました。"),
                        ("I was able to〜", "仕事", "I was able to reach the client.", "クライアントに連絡できました。"),
                        ("I was able to〜", "仕事", "I was able to negotiate a good deal.", "良い取引の交渉ができました。"),
                        ("I was able to〜", "学習", "I was able to understand the grammar.", "文法を理解できました。"),
                        ("I was able to〜", "学習", "I was able to memorize the vocabulary.", "単語を覚えられました。"),
                        ("I was able to〜", "学習", "I was able to pass the test.", "テストに合格できました。"),
                        ("I was able to〜", "学習", "I was able to write an essay.", "エッセイを書くことができました。"),
                        ("I was able to〜", "学習", "I was able to solve the problem.", "問題を解けました。"),
                        ("I was able to〜", "経験", "I was able to visit Kyoto.", "京都を訪れることができました。"),
                        ("I was able to〜", "経験", "I was able to try new food.", "新しい料理を試せました。"),
                        ("I was able to〜", "経験", "I was able to climb the mountain.", "山に登ることができました。"),
                        ("I was able to〜", "経験", "I was able to see the sunrise.", "日の出を見ることができました。"),
                        ("I was able to〜", "経験", "I was able to take amazing photos.", "素敵な写真を撮ることができました。"),
                        ("I was able to〜", "人間関係", "I was able to say thank you.", "ありがとうと言えました。"),
                        ("I was able to〜", "人間関係", "I was able to apologize to her.", "彼女に謝ることができました。"),
                        ("I was able to〜", "人間関係", "I was able to express my feelings.", "自分の気持ちを伝えられました。"),
                        ("I was able to〜", "人間関係", "I was able to comfort my friend.", "友達を慰めることができました。"),
                        ("I was able to〜", "人間関係", "I was able to reconnect with an old friend.", "昔の友人と再会できました。"),
                        
            // MARK: - I could ~
                        ("I could〜", "日常", "I could go for a walk.", "散歩に行ってもいいかも。"),
                        ("I could〜", "日常", "I could make some tea.", "お茶を入れようかな。"),
                        ("I could〜", "日常", "I could cook dinner tonight.", "今夜は私が夕飯作ろうか。"),
                        ("I could〜", "日常", "I could help you with that.", "それ、手伝えるかも。"),
                        ("I could〜", "日常", "I could stay home today.", "今日は家にいようかな。"),
                        ("I could〜", "仕事", "I could join the meeting.", "その会議に参加できそうです。"),
                        ("I could〜", "仕事", "I could finish this by noon.", "これを正午までに終えられるかもしれません。"),
                        ("I could〜", "仕事", "I could send the report later.", "後で報告書を送ることができます。"),
                        ("I could〜", "仕事", "I could talk to the manager.", "マネージャーに話してみましょうか？"),
                        ("I could〜", "仕事", "I could cover for you tomorrow.", "明日、代わりに入れるかも。"),
                        ("I could〜", "学習", "I could understand the grammar.", "その文法を理解できました。"),
                        ("I could〜", "学習", "I could solve the problem.", "その問題を解けました。"),
                        ("I could〜", "学習", "I could answer all the questions.", "すべての質問に答えられました。"),
                        ("I could〜", "学習", "I could study more if I had time.", "時間があれば、もっと勉強できるのに。"),
                        ("I could〜", "学習", "I could read this book again.", "この本をもう一度読んでもいいかも。"),
                        ("I could〜", "提案", "I could help you with your homework.", "宿題を手伝えるよ。"),
                        ("I could〜", "提案", "I could drive you there.", "そこまで車で送ろうか？"),
                        ("I could〜", "提案", "I could show you around the city.", "街を案内できるよ。"),
                        ("I could〜", "提案", "I could make some coffee.", "コーヒー入れようか？"),
                        ("I could〜", "提案", "I could stay a bit longer.", "もう少しだけいようか？"),
                        ("I could〜", "人間関係", "I could talk to him about it.", "彼にそのことを話してみようかな。"),
                        ("I could〜", "人間関係", "I could say sorry.", "謝ってもいいかもしれない。"),
                        ("I could〜", "人間関係", "I could be more understanding.", "もっと理解を示せたかもしれない。"),
                        ("I could〜", "人間関係", "I could’ve been nicer.", "もっと優しくできたかも。"),
                        ("I could〜", "人間関係", "I could help her if she asks.", "頼まれたら彼女を手伝えるかも。"),
                        
            // MARK: - I should ~
                        ("I should〜", "日常", "I should clean my room.", "部屋を掃除したほうがいい。"),
                        ("I should〜", "日常", "I should go to bed early.", "早く寝たほうがいい。"),
                        ("I should〜", "日常", "I should drink more water.", "もっと水を飲んだほうがいい。"),
                        ("I should〜", "日常", "I should exercise more.", "もっと運動したほうがいい。"),
                        ("I should〜", "日常", "I should do the laundry.", "洗濯したほうがいい。"),
                        ("I should〜", "仕事", "I should check my email.", "メールを確認したほうがいい。"),
                        ("I should〜", "仕事", "I should attend that meeting.", "その会議に出席したほうがいい。"),
                        ("I should〜", "仕事", "I should talk to my boss.", "上司に話したほうがいい。"),
                        ("I should〜", "仕事", "I should finish this today.", "今日中にこれを終わらせたほうがいい。"),
                        ("I should〜", "仕事", "I should follow up with the client.", "クライアントにフォローしたほうがいい。"),
                        ("I should〜", "健康", "I should eat more vegetables.", "もっと野菜を食べたほうがいい。"),
                        ("I should〜", "健康", "I should stop eating junk food.", "ジャンクフードをやめたほうがいい。"),
                        ("I should〜", "健康", "I should go to the doctor.", "病院に行ったほうがいい。"),
                        ("I should〜", "健康", "I should stretch every morning.", "毎朝ストレッチしたほうがいい。"),
                        ("I should〜", "健康", "I should walk more.", "もっと歩いたほうがいい。"),
                        ("I should〜", "思考", "I should think before I speak.", "話す前に考えたほうがいい。"),
                        ("I should〜", "思考", "I should focus on the positive.", "ポジティブに集中したほうがいい。"),
                        ("I should〜", "思考", "I should stop overthinking.", "考えすぎるのをやめたほうがいい。"),
                        ("I should〜", "思考", "I should be more confident.", "もっと自信を持ったほうがいい。"),
                        ("I should〜", "思考", "I should let it go.", "それはもう手放したほうがいい。"),
                        ("I should〜", "人間関係", "I should apologize to her.", "彼女に謝ったほうがいい。"),
                        ("I should〜", "人間関係", "I should talk to him.", "彼と話したほうがいい。"),
                        ("I should〜", "人間関係", "I should be more honest.", "もっと正直になったほうがいい。"),
                        ("I should〜", "人間関係", "I should spend more time with my family.", "家族ともっと時間を過ごしたほうがいい。"),
                        ("I should〜", "人間関係", "I should forgive him.", "彼を許したほうがいい。"),
                        

           // MARK: - I will 〜
                        ("I will〜", "日常", "I will do the laundry.", "洗濯をします。"),
                        ("I will〜", "日常", "I will clean my room.", "部屋を掃除します。"),
                        ("I will〜", "日常", "I will cook dinner tonight.", "今夜は夕食を作ります。"),
                        ("I will〜", "日常", "I will go shopping later.", "あとで買い物に行きます。"),
                        ("I will〜", "日常", "I will take out the trash.", "ゴミを出してきます。"),
                        ("I will〜", "仕事", "I will send the email now.", "今すぐメールを送ります。"),
                        ("I will〜", "仕事", "I will join the meeting.", "会議に参加します。"),
                        ("I will〜", "仕事", "I will finish this by 5.", "5時までにこれを終わらせます。"),
                        ("I will〜", "仕事", "I will contact the client.", "クライアントに連絡します。"),
                        ("I will〜", "仕事", "I will make the presentation slides.", "プレゼンのスライドを作ります。"),
                        ("I will〜", "学習", "I will study English every day.", "毎日英語を勉強します。"),
                        ("I will〜", "学習", "I will review grammar tonight.", "今夜は文法を復習します。"),
                        ("I will〜", "学習", "I will read one chapter a day.", "1日1章読みます。"),
                        ("I will〜", "学習", "I will memorize 10 new words.", "新しい単語を10個覚えます。"),
                        ("I will〜", "学習", "I will practice speaking English.", "英会話の練習をします。"),
                        ("I will〜", "決意", "I will never give up.", "絶対にあきらめません。"),
                        ("I will〜", "決意", "I will do my best.", "ベストを尽くします。"),
                        ("I will〜", "決意", "I will try again.", "もう一度やってみます。"),
                        ("I will〜", "決意", "I will change my life.", "人生を変えます。"),
                        ("I will〜", "決意", "I will save more money.", "もっとお金を貯めます。"),
                        ("I will〜", "人間関係", "I will be kind to others.", "人に優しくします。"),
                        ("I will〜", "人間関係", "I will say thank you.", "ありがとうと言います。"),
                        ("I will〜", "人間関係", "I will talk to her.", "彼女に話しかけます。"),
                        ("I will〜", "人間関係", "I will forgive him.", "彼を許します。"),
                        ("I will〜", "人間関係", "I will help my friend.", "友達を助けます。"),
                        
            // MARK: - I would 〜
                        ("I would〜", "日常", "I would like some coffee.", "コーヒーをいただきたいです。"),
                        ("I would〜", "日常", "I would love to go with you.", "ぜひ一緒に行きたいです。"),
                        ("I would〜", "日常", "I would like to try that.", "それを試してみたいです。"),
                        ("I would〜", "日常", "I would prefer tea over coffee.", "コーヒーより紅茶がいいです。"),
                        ("I would〜", "日常", "I would like to order this.", "これを注文したいです。"),
                        ("I would〜", "仕事", "I would like to schedule a meeting.", "会議の予定を立てたいです。"),
                        ("I would〜", "仕事", "I would be happy to assist you.", "喜んでお手伝いします。"),
                        ("I would〜", "仕事", "I would recommend this solution.", "この解決策をおすすめします。"),
                        ("I would〜", "仕事", "I would like to hear your thoughts.", "あなたの意見をお聞きしたいです。"),
                        ("I would〜", "仕事", "I would appreciate your feedback.", "フィードバックをいただけると嬉しいです。"),
                        ("I would〜", "仮定", "I would go if I had time.", "時間があれば行くのに。"),
                        ("I would〜", "仮定", "I would help you, but I'm busy.", "手伝いたいけど忙しいんです。"),
                        ("I would〜", "仮定", "I would buy it if it were cheaper.", "もっと安ければ買うのに。"),
                        ("I would〜", "仮定", "I would travel the world if I won the lottery.", "宝くじに当たったら世界旅行したい。"),
                        ("I would〜", "仮定", "I would call her, but she’s asleep.", "電話したいけど、彼女は寝てるんです。"),
                        ("I would〜", "感情", "I would never lie to you.", "あなたには絶対に嘘をつきません。"),
                        ("I would〜", "感情", "I would always support you.", "いつでもあなたを応援します。"),
                        ("I would〜", "感情", "I would do anything for you.", "あなたのためなら何でもします。"),
                        ("I would〜", "感情", "I would miss you so much.", "あなたがいなくてとても寂しくなると思う。"),
                        ("I would〜", "感情", "I would like to know more about you.", "あなたのことをもっと知りたいです。"),
                        ("I would〜", "思考", "I would say that’s a good idea.", "それはいいアイデアだと思います。"),
                        ("I would〜", "思考", "I would choose the red one.", "赤い方を選びます。"),
                        ("I would〜", "思考", "I would avoid that situation.", "その状況は避けたいですね。"),
                        ("I would〜", "思考", "I would take the job offer.", "その仕事のオファーを受けます。"),
                        ("I would〜", "思考", "I would change a few things.", "いくつか変えると思います。"),
                        
            // MARK: - I would like to ~
                        ("I would like to〜", "日常", "I would like to drink some water.", "水を飲みたいです。"),
                        ("I would like to〜", "日常", "I would like to take a nap.", "昼寝をしたいです。"),
                        ("I would like to〜", "日常", "I would like to go for a walk.", "散歩に行きたいです。"),
                        ("I would like to〜", "日常", "I would like to eat sushi.", "寿司を食べたいです。"),
                        ("I would like to〜", "日常", "I would like to watch a movie tonight.", "今夜は映画を観たいです。"),
                        ("I would like to〜", "仕事", "I would like to schedule a meeting.", "会議の予定を立てたいです。"),
                        ("I would like to〜", "仕事", "I would like to speak with the manager.", "マネージャーと話したいです。"),
                        ("I would like to〜", "仕事", "I would like to apply for this position.", "このポジションに応募したいです。"),
                        ("I would like to〜", "仕事", "I would like to discuss the details.", "詳細について話し合いたいです。"),
                        ("I would like to〜", "仕事", "I would like to update the report.", "報告書を更新したいです。"),
                        ("I would like to〜", "学習", "I would like to study English every day.", "毎日英語を勉強したいです。"),
                        ("I would like to〜", "学習", "I would like to read more books.", "もっと本を読みたいです。"),
                        ("I would like to〜", "学習", "I would like to practice speaking.", "スピーキングの練習をしたいです。"),
                        ("I would like to〜", "学習", "I would like to write a diary in English.", "英語で日記を書きたいです。"),
                        ("I would like to〜", "学習", "I would like to improve my vocabulary.", "語彙力を伸ばしたいです。"),
                        ("I would like to〜", "旅行", "I would like to visit Kyoto.", "京都を訪れたいです。"),
                        ("I would like to〜", "旅行", "I would like to travel abroad.", "海外旅行をしたいです。"),
                        ("I would like to〜", "旅行", "I would like to stay at a traditional inn.", "旅館に泊まりたいです。"),
                        ("I would like to〜", "旅行", "I would like to try local food.", "地元の料理を食べたいです。"),
                        ("I would like to〜", "旅行", "I would like to see the cherry blossoms.", "桜を見たいです。"),
                        ("I would like to〜", "人間関係", "I would like to talk to you.", "あなたと話したいです。"),
                        ("I would like to〜", "人間関係", "I would like to say thank you.", "ありがとうと言いたいです。"),
                        ("I would like to〜", "人間関係", "I would like to get to know you better.", "あなたのことをもっと知りたいです。"),
                        ("I would like to〜", "人間関係", "I would like to apologize.", "謝りたいです。"),
                        ("I would like to〜", "人間関係", "I would like to support my friend.", "友達をサポートしたいです。"),
                        
            // MARK: - would you like to ~
                        ("Would you like to〜", "日常", "Would you like to go for a walk?", "散歩に行きませんか？"),
                        ("Would you like to〜", "日常", "Would you like to have lunch together?", "一緒にランチしませんか？"),
                        ("Would you like to〜", "日常", "Would you like to come over?", "うちに来ませんか？"),
                        ("Would you like to〜", "日常", "Would you like to go shopping?", "買い物に行きませんか？"),
                        ("Would you like to〜", "日常", "Would you like to watch a movie?", "映画を観ませんか？"),
                        ("Would you like to〜", "仕事", "Would you like to schedule a meeting?", "会議を設定しませんか？"),
                        ("Would you like to〜", "仕事", "Would you like to join the project?", "そのプロジェクトに参加しませんか？"),
                        ("Would you like to〜", "仕事", "Would you like to take the lead?", "リーダーを引き受けませんか？"),
                        ("Would you like to〜", "仕事", "Would you like to share your opinion?", "意見を共有しませんか？"),
                        ("Would you like to〜", "仕事", "Would you like to review the document?", "書類を確認しませんか？"),
                        ("Would you like to〜", "食事", "Would you like to have some tea?", "お茶を飲みませんか？"),
                        ("Would you like to〜", "食事", "Would you like to try this dish?", "この料理を試してみませんか？"),
                        ("Would you like to〜", "食事", "Would you like to eat out tonight?", "今夜外食しませんか？"),
                        ("Would you like to〜", "食事", "Would you like to cook together?", "一緒に料理しませんか？"),
                        ("Would you like to〜", "食事", "Would you like to order something?", "何か注文しませんか？"),
                        ("Would you like to〜", "旅行", "Would you like to visit Kyoto?", "京都を訪れませんか？"),
                        ("Would you like to〜", "旅行", "Would you like to travel this weekend?", "今週末に旅行しませんか？"),
                        ("Would you like to〜", "旅行", "Would you like to go to the beach?", "ビーチに行きませんか？"),
                        ("Would you like to〜", "旅行", "Would you like to go hiking?", "ハイキングに行きませんか？"),
                        ("Would you like to〜", "旅行", "Would you like to take a day trip?", "日帰り旅行しませんか？"),
                        ("Would you like to〜", "丁寧", "Would you like to sit down?", "お座りになりませんか？"),
                        ("Would you like to〜", "丁寧", "Would you like to use my phone?", "私の携帯を使いますか？"),
                        ("Would you like to〜", "丁寧", "Would you like to take a break?", "休憩しませんか？"),
                        ("Would you like to〜", "丁寧", "Would you like to borrow this book?", "この本を借りますか？"),
                        ("Would you like to〜", "丁寧", "Would you like to come with us?", "一緒に来ませんか？"),
                        
            // MARK: - I'm 〇〇ing ~
                        ("I'm ◯◯ing", "日常", "I'm cooking dinner.", "夕食を作ってるところです。"),
                        ("I'm ◯◯ing", "日常", "I'm cleaning my room.", "部屋を掃除してるところです。"),
                        ("I'm ◯◯ing", "日常", "I'm watching TV.", "テレビを観てるところです。"),
                        ("I'm ◯◯ing", "日常", "I'm doing the laundry.", "洗濯してるところです。"),
                        ("I'm ◯◯ing", "日常", "I'm brushing my teeth.", "歯を磨いてます。"),
                        ("I'm ◯◯ing", "仕事", "I'm working from home.", "在宅勤務中です。"),
                        ("I'm ◯◯ing", "仕事", "I'm checking my email.", "メールをチェックしています。"),
                        ("I'm ◯◯ing", "仕事", "I'm attending a meeting.", "会議に出ています。"),
                        ("I'm ◯◯ing", "仕事", "I'm writing a report.", "レポートを書いています。"),
                        ("I'm ◯◯ing", "仕事", "I'm talking to my boss.", "上司と話しています。"),
                        ("I'm ◯◯ing", "移動", "I'm walking to the station.", "駅に歩いて向かってます。"),
                        ("I'm ◯◯ing", "移動", "I'm driving to work.", "仕事に車で向かっています。"),
                        ("I'm ◯◯ing", "移動", "I'm getting on the train.", "電車に乗るところです。"),
                        ("I'm ◯◯ing", "移動", "I'm heading to the cafe.", "カフェに向かっているところです。"),
                        ("I'm ◯◯ing", "移動", "I'm waiting for the bus.", "バスを待っています。"),
                        ("I'm ◯◯ing", "その他", "I'm taking a break.", "休憩しています。"),
                        ("I'm ◯◯ing", "その他", "I'm trying something new.", "新しいことに挑戦しています。"),
                        ("I'm ◯◯ing", "その他", "I'm fixing the problem.", "問題を修正しています。"),
                        ("I'm ◯◯ing", "その他", "I'm helping my friend.", "友達を手伝っています。"),
                        ("I'm ◯◯ing", "その他", "I'm planning a trip.", "旅行の計画をしています。"),
                        ("I'm ◯◯ing", "感情", "I'm feeling great today.", "今日は気分がとても良いです。"),
                        ("I'm ◯◯ing", "感情", "I'm getting tired.", "疲れてきました。"),
                        ("I'm ◯◯ing", "感情", "I'm feeling a bit sick.", "少し体調が悪いです。"),
                        ("I'm ◯◯ing", "感情", "I'm getting nervous.", "緊張してきています。"),
                        ("I'm ◯◯ing", "感情", "I'm feeling relaxed.", "リラックスしています。"),
                        
            // MARK: - I have to ~
                        ("I have to〜", "日常", "I have to wake up early.", "早起きしないといけません。"),
                        ("I have to〜", "日常", "I have to take a shower.", "シャワーを浴びなきゃ。"),
                        ("I have to〜", "日常", "I have to do the laundry.", "洗濯しなきゃ。"),
                        ("I have to〜", "日常", "I have to clean my room.", "部屋を掃除しないと。"),
                        ("I have to〜", "日常", "I have to go shopping.", "買い物に行かないと。"),
                        ("I have to〜", "仕事", "I have to finish this report.", "この報告書を仕上げないといけません。"),
                        ("I have to〜", "仕事", "I have to attend a meeting.", "会議に出席しないといけません。"),
                        ("I have to〜", "仕事", "I have to send an email.", "メールを送らないといけません。"),
                        ("I have to〜", "仕事", "I have to call my client.", "クライアントに電話しなければなりません。"),
                        ("I have to〜", "仕事", "I have to prepare the documents.", "書類を準備しないと。"),
                        ("I have to〜", "学習", "I have to study English.", "英語を勉強しないといけません。"),
                        ("I have to〜", "学習", "I have to memorize these words.", "これらの単語を覚えないと。"),
                        ("I have to〜", "学習", "I have to do my homework.", "宿題をやらないと。"),
                        ("I have to〜", "学習", "I have to prepare for the exam.", "試験の準備をしないと。"),
                        ("I have to〜", "学習", "I have to practice speaking.", "スピーキングの練習をしないと。"),
                        ("I have to〜", "義務", "I have to follow the rules.", "ルールに従わないと。"),
                        ("I have to〜", "義務", "I have to be on time.", "時間通りに行かないと。"),
                        ("I have to〜", "義務", "I have to pay the rent.", "家賃を払わないと。"),
                        ("I have to〜", "義務", "I have to renew my license.", "免許を更新しなければなりません。"),
                        ("I have to〜", "義務", "I have to wear a mask.", "マスクをしないといけません。"),
                        ("I have to〜", "その他", "I have to leave now.", "もう出発しないと。"),
                        ("I have to〜", "その他", "I have to go to the doctor.", "病院に行かないと。"),
                        ("I have to〜", "その他", "I have to cancel my plan.", "予定をキャンセルしないと。"),
                        ("I have to〜", "その他", "I have to call my mom.", "母に電話しないと。"),
                        ("I have to〜", "その他", "I have to be careful.", "気をつけないと。"),
                        
            // MARK: - I want to ~
                        ("I want to〜", "日常", "I want to eat something sweet.", "甘いものが食べたい。"),
                        ("I want to〜", "日常", "I want to take a nap.", "昼寝したい。"),
                        ("I want to〜", "日常", "I want to drink coffee.", "コーヒーが飲みたい。"),
                        ("I want to〜", "日常", "I want to clean my room.", "部屋を掃除したい。"),
                        ("I want to〜", "日常", "I want to go out for dinner.", "夕食を食べに出かけたい。"),
                        ("I want to〜", "仕事", "I want to finish this project.", "このプロジェクトを終わらせたい。"),
                        ("I want to〜", "仕事", "I want to learn a new skill.", "新しいスキルを身につけたい。"),
                        ("I want to〜", "仕事", "I want to work overseas.", "海外で働きたい。"),
                        ("I want to〜", "仕事", "I want to talk to my boss.", "上司と話したい。"),
                        ("I want to〜", "仕事", "I want to change my job.", "転職したい。"),
                        ("I want to〜", "趣味", "I want to play the guitar.", "ギターを弾きたい。"),
                        ("I want to〜", "趣味", "I want to go hiking.", "ハイキングに行きたい。"),
                        ("I want to〜", "趣味", "I want to draw something.", "何か絵を描きたい。"),
                        ("I want to〜", "趣味", "I want to try cooking.", "料理に挑戦してみたい。"),
                        ("I want to〜", "趣味", "I want to go to a concert.", "コンサートに行きたい。"),
                        ("I want to〜", "感情", "I want to make new friends.", "新しい友達を作りたい。"),
                        ("I want to〜", "感情", "I want to talk to you.", "あなたと話したい。"),
                        ("I want to〜", "感情", "I want to be honest with you.", "あなたに正直になりたい。"),
                        ("I want to〜", "感情", "I want to be alone right now.", "今は一人でいたい。"),
                        ("I want to〜", "感情", "I want to spend more time with my family.", "家族ともっと時間を過ごしたい。"),
                        ("I want to〜", "将来", "I want to travel the world.", "世界を旅したい。"),
                        ("I want to〜", "将来", "I want to live abroad someday.", "いつか海外に住みたい。"),
                        ("I want to〜", "将来", "I want to start my own business.", "自分のビジネスを始めたい。"),
                        ("I want to〜", "将来", "I want to get married in the future.", "将来は結婚したい。"),
                        ("I want to〜", "将来", "I want to be a teacher.", "先生になりたい。"),
                        
            // MARK: - I'm going to ~
                        ("I'm going to〜", "日常", "I'm going to take a shower.", "シャワーを浴びるつもりです。"),
                        ("I'm going to〜", "日常", "I'm going to cook dinner.", "夕食を作るつもりです。"),
                        ("I'm going to〜", "日常", "I'm going to clean my room.", "部屋を掃除します。"),
                        ("I'm going to〜", "日常", "I'm going to do the laundry.", "洗濯します。"),
                        ("I'm going to〜", "日常", "I'm going to watch a movie tonight.", "今夜は映画を観る予定です。"),
                        ("I'm going to〜", "仕事", "I'm going to finish the report.", "レポートを仕上げるつもりです。"),
                        ("I'm going to〜", "仕事", "I'm going to send the email now.", "今メールを送るつもりです。"),
                        ("I'm going to〜", "仕事", "I'm going to attend the meeting.", "会議に参加します。"),
                        ("I'm going to〜", "仕事", "I'm going to talk to my manager.", "マネージャーと話す予定です。"),
                        ("I'm going to〜", "仕事", "I'm going to update the file.", "ファイルを更新します。"),
                        ("I'm going to〜", "旅行", "I'm going to visit Kyoto next weekend.", "来週末に京都に行きます。"),
                        ("I'm going to〜", "旅行", "I'm going to travel to Okinawa.", "沖縄に旅行します。"),
                        ("I'm going to〜", "旅行", "I'm going to take a trip with my family.", "家族と旅行に行くつもりです。"),
                        ("I'm going to〜", "旅行", "I'm going to stay at a hotel.", "ホテルに泊まる予定です。"),
                        ("I'm going to〜", "旅行", "I'm going to ride the bullet train.", "新幹線に乗るつもりです。"),
                        ("I'm going to〜", "感情", "I'm going to talk to her about it.", "そのことについて彼女と話すつもりです。"),
                        ("I'm going to〜", "感情", "I'm going to apologize to him.", "彼に謝るつもりです。"),
                        ("I'm going to〜", "感情", "I'm going to tell them how I feel.", "自分の気持ちを伝えるつもりです。"),
                        ("I'm going to〜", "感情", "I'm going to be honest with you.", "正直に話すつもりです。"),
                        ("I'm going to〜", "感情", "I'm going to spend more time with my family.", "家族との時間をもっと大切にするつもりです。"),
                        ("I'm going to〜", "将来", "I'm going to start my own business.", "自分のビジネスを始めるつもりです。"),
                        ("I'm going to〜", "将来", "I'm going to become a teacher.", "先生になるつもりです。"),
                        ("I'm going to〜", "将来", "I'm going to learn programming.", "プログラミングを学ぶつもりです。"),
                        ("I'm going to〜", "将来", "I'm going to improve my English.", "英語を上達させるつもりです。"),
                        ("I'm going to〜", "将来", "I'm going to study abroad.", "留学するつもりです。"),
                        
            // MARK: - Have you ~
                        ("Have you〜", "日常", "Have you ever forgotten something important?", "大事なことを忘れたことありますか？"),
                        ("Have you〜", "日常", "Have you ever lost your phone?", "スマホをなくしたことありますか？"),
                        ("Have you〜", "日常", "Have you ever been late for work?", "仕事に遅刻したことありますか？"),
                        ("Have you〜", "日常", "Have you locked the door?", "ドアに鍵をかけましたか？"),
                        ("Have you〜", "日常", "Have you seen my bag?", "私のカバンを見ましたか？"),
                        ("Have you〜", "経験", "Have you ever been to Japan?", "日本に行ったことがありますか？"),
                        ("Have you〜", "経験", "Have you ever eaten sushi?", "寿司を食べたことがありますか？"),
                        ("Have you〜", "経験", "Have you ever seen a shooting star?", "流れ星を見たことありますか？"),
                        ("Have you〜", "経験", "Have you ever ridden a horse?", "馬に乗ったことありますか？"),
                        ("Have you〜", "経験", "Have you ever climbed a mountain?", "山に登ったことありますか？"),
                        ("Have you〜", "最近", "Have you eaten lunch yet?", "もう昼ごはん食べましたか？"),
                        ("Have you〜", "最近", "Have you finished your homework?", "宿題終わりましたか？"),
                        ("Have you〜", "最近", "Have you seen the news today?", "今日のニュース見ましたか？"),
                        ("Have you〜", "最近", "Have you heard about the event?", "そのイベントのこと聞きましたか？"),
                        ("Have you〜", "最近", "Have you talked to him today?", "今日彼と話しましたか？"),
                        ("Have you〜", "趣味", "Have you watched this movie?", "この映画見ましたか？"),
                        ("Have you〜", "趣味", "Have you listened to this song?", "この曲を聴いたことありますか？"),
                        ("Have you〜", "趣味", "Have you played this game?", "このゲームやったことありますか？"),
                        ("Have you〜", "趣味", "Have you tried this app?", "このアプリ試しましたか？"),
                        ("Have you〜", "趣味", "Have you gone to that restaurant?", "あのレストランに行きましたか？"),
                        ("Have you〜", "健康", "Have you seen a doctor?", "医者に行きましたか？"),
                        ("Have you〜", "健康", "Have you taken your medicine?", "薬は飲みましたか？"),
                        ("Have you〜", "健康", "Have you been feeling okay?", "体調は大丈夫ですか？"),
                        ("Have you〜", "健康", "Have you gotten enough sleep?", "十分に眠れましたか？"),
                        ("Have you〜", "健康", "Have you exercised today?", "今日は運動しましたか？"),
                      
                        
            // MARK: - Let me ~
                        ("Let me〜", "日常", "Let me help you.", "手伝わせてください。"),
                        ("Let me〜", "日常", "Let me carry that for you.", "それを運ばせてください。"),
                        ("Let me〜", "日常", "Let me get that for you.", "それを取ってきますね。"),
                        ("Let me〜", "日常", "Let me check.", "ちょっと確認しますね。"),
                        ("Let me〜", "日常", "Let me show you.", "見せてあげますね。"),
                        ("Let me〜", "申し出", "Let me take care of it.", "それは私に任せてください。"),
                        ("Let me〜", "申し出", "Let me know your opinion.", "ご意見を聞かせてください。"),
                        ("Let me〜", "申し出", "Let me handle this part.", "この部分を私にやらせてください。"),
                        ("Let me〜", "申し出", "Let me introduce myself.", "自己紹介させてください。"),
                        ("Let me〜", "申し出", "Let me call you back.", "折り返し電話させてください。"),
                        ("Let me〜", "仕事", "Let me send you the file.", "そのファイルを送らせてください。"),
                        ("Let me〜", "仕事", "Let me double-check that.", "それを再確認させてください。"),
                        ("Let me〜", "仕事", "Let me schedule the meeting.", "会議の予定を組ませてください。"),
                        ("Let me〜", "仕事", "Let me contact the client.", "クライアントに連絡させてください。"),
                        ("Let me〜", "仕事", "Let me update the document.", "書類を更新させてください。"),
                        ("Let me〜", "カジュアル", "Let me know how it goes.", "どうだったか教えてね。"),
                        ("Let me〜", "カジュアル", "Let me take a photo.", "写真撮らせて！"),
                        ("Let me〜", "カジュアル", "Let me try!", "やらせて！"),
                        ("Let me〜", "カジュアル", "Let me join you.", "一緒にやらせて！"),
                        ("Let me〜", "カジュアル", "Let me borrow your charger.", "充電器貸して！"),
                        ("Let me〜", "その他", "Let me make it clear.", "はっきりさせてください。"),
                        ("Let me〜", "その他", "Let me say this first.", "先にこれを言わせてください。"),
                        ("Let me〜", "その他", "Let me try again.", "もう一度やらせてください。"),
                        ("Let me〜", "その他", "Let me know your schedule.", "スケジュールを教えてください。"),
                        ("Let me〜", "その他", "Let me know if you agree.", "同意なら教えてください。"),
                        
                        
            // MARK: - There is ~
                        ("There is", "日常", "There is a cup on the table.", "テーブルの上にカップがあります。"),
                        ("There is", "日常", "There is a key under the chair.", "椅子の下に鍵があります。"),
                        ("There is", "旅行", "There is a convenience store near the hotel.", "ホテルの近くにコンビニがあります。"),
                        ("There is", "旅行", "There is a station around the corner.", "角を曲がったところに駅があります。"),
                        ("There is", "学校", "There is a test tomorrow.", "明日テストがあります。"),
                        ("There is", "学校", "There is a new student in our class.", "クラスに新しい生徒がいます。"),
                        ("There is", "仕事", "There is a meeting at 3 p.m.", "午後3時に会議があります。"),
                        ("There is", "仕事", "There is a problem with the system.", "システムに問題があります。"),
                        ("There is", "その他", "There is nothing we can do now.", "今できることは何もありません。"),
                        ("There is", "その他", "There is something wrong.", "何かがおかしいです。"),
                        
                        
            // MARK: -  There are ~
                        ("There are", "日常", "There are shoes at the entrance.", "玄関に靴があります。"),
                        ("There are", "日常", "There are some dishes in the sink.", "シンクに皿がいくつかあります。"),
                        ("There are", "日常", "There are people outside.", "外に人がいます。"),
                        ("There are", "旅行", "There are a lot of tourists here.", "ここには観光客がたくさんいます。"),
                        ("There are", "旅行", "There are many restaurants in this area.", "このエリアにはレストランが多いです。"),
                        ("There are", "旅行", "There are several buses every hour.", "毎時間いくつかバスがあります。"),
                        ("There are", "学校", "There are 20 students in the class.", "クラスには20人の生徒がいます。"),
                        ("There are", "学校", "There are many books in the library.", "図書館にはたくさんの本があります。"),
                        ("There are", "学校", "There are questions on the test.", "テストには質問があります。"),
                        ("There are", "仕事", "There are documents to print.", "印刷する書類があります。"),
                        ("There are", "仕事", "There are some issues we need to fix.", "修正すべき問題があります。"),
                        ("There are", "仕事", "There are many emails to reply to.", "返信すべきメールがたくさんあります。"),
                        ("There are", "その他", "There are so many options.", "たくさんの選択肢があります。"),
                        ("There are", "その他", "There are no mistakes in this file.", "このファイルにはミスがありません。"),
                        ("There are", "その他", "There are things we need to discuss.", "話し合うべきことがあります。"),
                        
        // MARK: - I forgot to ~
                        ("I forgot to〜", "日常", "I forgot to lock the door.", "ドアに鍵をかけるのを忘れました。"),
                        ("I forgot to〜", "日常", "I forgot to turn off the lights.", "電気を消すのを忘れました。"),
                        ("I forgot to〜", "日常", "I forgot to take out the trash.", "ゴミを出すのを忘れました。"),
                        ("I forgot to〜", "日常", "I forgot to bring my wallet.", "財布を持ってくるのを忘れました。"),
                        ("I forgot to〜", "日常", "I forgot to feed the cat.", "猫にごはんをあげるのを忘れました。"),
                        ("I forgot to〜", "仕事", "I forgot to send the email.", "メールを送るのを忘れました。"),
                        ("I forgot to〜", "仕事", "I forgot to attach the file.", "ファイルを添付するのを忘れました。"),
                        ("I forgot to〜", "仕事", "I forgot to print the report.", "レポートを印刷するのを忘れました。"),
                        ("I forgot to〜", "仕事", "I forgot to submit the document.", "書類を提出するのを忘れました。"),
                        ("I forgot to〜", "仕事", "I forgot to write it down.", "メモするのを忘れました。"),
                        ("I forgot to〜", "勉強", "I forgot to do my homework.", "宿題をするのを忘れました。"),
                        ("I forgot to〜", "勉強", "I forgot to bring my textbook.", "教科書を持ってくるのを忘れました。"),
                        ("I forgot to〜", "勉強", "I forgot to study for the test.", "テスト勉強をするのを忘れました。"),
                        ("I forgot to〜", "勉強", "I forgot to write my name.", "名前を書くのを忘れました。"),
                        ("I forgot to〜", "勉強", "I forgot to check the schedule.", "スケジュールを確認するのを忘れました。"),
                        ("I forgot to〜", "外出", "I forgot to bring my umbrella.", "傘を持ってくるのを忘れました。"),
                        ("I forgot to〜", "外出", "I forgot to charge my phone.", "スマホを充電するのを忘れました。"),
                        ("I forgot to〜", "外出", "I forgot to buy a ticket.", "チケットを買うのを忘れました。"),
                        ("I forgot to〜", "外出", "I forgot to check the train schedule.", "電車の時刻を確認するのを忘れました。"),
                        ("I forgot to〜", "外出", "I forgot to bring my ID.", "身分証を持ってくるのを忘れました。"),
                        ("I forgot to〜", "その他", "I forgot to tell you something.", "あなたに言うことを忘れてました。"),
                        ("I forgot to〜", "その他", "I forgot to say thank you.", "お礼を言うのを忘れていました。"),
                        ("I forgot to〜", "その他", "I forgot to bring your present.", "あなたへのプレゼントを持ってくるのを忘れました。"),
                        ("I forgot to〜", "その他", "I forgot to invite her.", "彼女を招待するのを忘れました。"),
                        ("I forgot to〜", "その他", "I forgot to turn off the gas.", "ガスを消すのを忘れました。"),
                        
            // MARK: - I use to ~
                        ("I used to〜", "習慣", "I used to get up early.", "昔は早起きしていました。"),
                        ("I used to〜", "習慣", "I used to drink coffee every morning.", "毎朝コーヒーを飲んでいました。"),
                        ("I used to〜", "習慣", "I used to eat fast food a lot.", "昔はよくファストフードを食べていました。"),
                        ("I used to〜", "習慣", "I used to go jogging every day.", "毎日ジョギングしていました。"),
                        ("I used to〜", "習慣", "I used to smoke.", "昔はタバコを吸っていました。"),
                        ("I used to〜", "学校", "I used to study English every day.", "毎日英語を勉強していました。"),
                        ("I used to〜", "学校", "I used to go to cram school.", "塾に通っていました。"),
                        ("I used to〜", "学校", "I used to be shy in class.", "クラスでは恥ずかしがり屋でした。"),
                        ("I used to〜", "学校", "I used to eat lunch alone.", "昼食は一人で食べていました。"),
                        ("I used to〜", "学校", "I used to hate math.", "数学が嫌いでした。"),
                        ("I used to〜", "仕事", "I used to work late every night.", "毎晩遅くまで働いていました。"),
                        ("I used to〜", "仕事", "I used to be a teacher.", "教師をしていました。"),
                        ("I used to〜", "仕事", "I used to work in Tokyo.", "東京で働いていました。"),
                        ("I used to〜", "仕事", "I used to have a different job.", "以前は違う仕事をしていました。"),
                        ("I used to〜", "仕事", "I used to take the train to work.", "通勤に電車を使っていました。"),
                        ("I used to〜", "家族", "I used to live with my parents.", "両親と一緒に住んでいました。"),
                        ("I used to〜", "家族", "I used to visit my grandparents often.", "祖父母の家によく行っていました。"),
                        ("I used to〜", "家族", "I used to play with my little brother.", "弟とよく遊んでいました。"),
                        ("I used to〜", "家族", "I used to argue with my sister.", "妹とよくケンカしていました。"),
                        ("I used to〜", "家族", "I used to live alone.", "一人暮らししていました。"),
                        ("I used to〜", "趣味", "I used to play the piano.", "ピアノを弾いていました。"),
                        ("I used to〜", "趣味", "I used to draw a lot.", "よく絵を描いていました。"),
                        ("I used to〜", "趣味", "I used to collect stamps.", "切手を集めていました。"),
                        ("I used to〜", "趣味", "I used to play video games all day.", "一日中ゲームをしていました。"),
                        ("I used to〜", "趣味", "I used to go hiking every weekend.", "毎週末ハイキングに行っていました。"),
                        
            // MARK: - I'm used to ~
                        ("I'm used to〜", "日常", "I'm used to waking up early.", "早起きに慣れています。"),
                        ("I'm used to〜", "日常", "I'm used to cold showers.", "冷たいシャワーに慣れています。"),
                        ("I'm used to〜", "日常", "I'm used to drinking black coffee.", "ブラックコーヒーを飲むのに慣れています。"),
                        ("I'm used to〜", "日常", "I'm used to cooking for myself.", "自炊に慣れています。"),
                        ("I'm used to〜", "日常", "I'm used to being alone.", "一人でいるのに慣れています。"),
                        ("I'm used to〜", "仕事", "I'm used to working overtime.", "残業に慣れています。"),
                        ("I'm used to〜", "仕事", "I'm used to dealing with clients.", "クライアント対応に慣れています。"),
                        ("I'm used to〜", "仕事", "I'm used to giving presentations.", "プレゼンに慣れています。"),
                        ("I'm used to〜", "仕事", "I'm used to working under pressure.", "プレッシャーの中で働くのに慣れています。"),
                        ("I'm used to〜", "仕事", "I'm used to using Excel every day.", "毎日Excelを使うのに慣れています。"),
                        ("I'm used to〜", "勉強", "I'm used to studying late at night.", "夜遅くまで勉強するのに慣れています。"),
                        ("I'm used to〜", "勉強", "I'm used to doing a lot of homework.", "宿題の多さに慣れています。"),
                        ("I'm used to〜", "勉強", "I'm used to taking notes in English.", "英語でノートを取るのに慣れています。"),
                        ("I'm used to〜", "勉強", "I'm used to taking online classes.", "オンライン授業に慣れています。"),
                        ("I'm used to〜", "勉強", "I'm used to speaking in front of the class.", "クラスの前で話すことに慣れています。"),
                        ("I'm used to〜", "感情", "I'm used to being busy.", "忙しいのに慣れています。"),
                        ("I'm used to〜", "感情", "I'm used to being misunderstood.", "誤解されるのに慣れています。"),
                        ("I'm used to〜", "感情", "I'm used to being ignored.", "無視されるのに慣れています。"),
                        ("I'm used to〜", "感情", "I'm used to helping others.", "人を助けるのに慣れています。"),
                        ("I'm used to〜", "感情", "I'm used to being the leader.", "リーダーになるのに慣れています。"),
                        ("I'm used to〜", "その他", "I'm used to this weather.", "この天気には慣れています。"),
                        ("I'm used to〜", "その他", "I'm used to city life.", "都会の生活に慣れています。"),
                        ("I'm used to〜", "その他", "I'm used to traveling alone.", "一人旅に慣れています。"),
                        ("I'm used to〜", "その他", "I'm used to using English every day.", "毎日英語を使うのに慣れています。"),
                        ("I'm used to〜", "その他", "I'm used to walking long distances.", "長距離を歩くのに慣れています。"),
                        
            // MARK: - I feel like 〜ing ~
                        ("I feel like 〜ing", "日常", "I feel like eating something sweet.", "甘いものが食べたい気分です。"),
                        ("I feel like 〜ing", "日常", "I feel like sleeping all day.", "一日中寝たい気分です。"),
                        ("I feel like 〜ing", "日常", "I feel like staying home today.", "今日は家にいたい気分です。"),
                        ("I feel like 〜ing", "日常", "I feel like watching a movie.", "映画を見たい気分です。"),
                        ("I feel like 〜ing", "日常", "I feel like drinking coffee.", "コーヒーを飲みたい気分です。"),
                        ("I feel like 〜ing", "食事", "I feel like eating ramen tonight.", "今夜はラーメンが食べたい気分です。"),
                        ("I feel like 〜ing", "食事", "I feel like cooking something spicy.", "辛い料理を作りたい気分です。"),
                        ("I feel like 〜ing", "食事", "I feel like trying a new restaurant.", "新しいレストランに行きたい気分です。"),
                        ("I feel like 〜ing", "食事", "I feel like having sushi.", "お寿司が食べたい気分です。"),
                        ("I feel like 〜ing", "食事", "I feel like making pancakes.", "パンケーキを作りたい気分です。"),
                        ("I feel like 〜ing", "感情", "I feel like crying.", "泣きたい気分です。"),
                        ("I feel like 〜ing", "感情", "I feel like laughing out loud.", "大声で笑いたい気分です。"),
                        ("I feel like 〜ing", "感情", "I feel like shouting.", "叫びたい気分です。"),
                        ("I feel like 〜ing", "感情", "I feel like giving up.", "あきらめたい気分です。"),
                        ("I feel like 〜ing", "感情", "I feel like talking to someone.", "誰かと話したい気分です。"),
                        ("I feel like 〜ing", "アクティビティ", "I feel like playing video games.", "ゲームをしたい気分です。"),
                        ("I feel like 〜ing", "アクティビティ", "I feel like going shopping.", "買い物に行きたい気分です。"),
                        ("I feel like 〜ing", "アクティビティ", "I feel like taking pictures.", "写真を撮りたい気分です。"),
                        ("I feel like 〜ing", "アクティビティ", "I feel like reading a book.", "本を読みたい気分です。"),
                        ("I feel like 〜ing", "アクティビティ", "I feel like learning something new.", "何か新しいことを学びたい気分です。"),
                        ("I feel like 〜ing", "その他", "I feel like trying something new.", "何か新しいことを試したい気分です。"),
                        ("I feel like 〜ing", "その他", "I feel like learning English.", "英語を学びたい気分です。"),
                        ("I feel like 〜ing", "その他", "I feel like writing a song.", "曲を書きたい気分です。"),
                        ("I feel like 〜ing", "その他", "I feel like changing my job.", "転職したい気分です。"),
                        ("I feel like 〜ing", "その他", "I feel like moving to a new city.", "新しい街に引っ越したい気分です。"),
                        
            // MARK: - I decided to ~
                        ("I decided to〜", "日常", "I decided to wake up early.", "早起きすることに決めました。"),
                        ("I decided to〜", "日常", "I decided to cook dinner tonight.", "今夜は夕食を作ることに決めました。"),
                        ("I decided to〜", "日常", "I decided to clean my room.", "部屋を掃除することに決めました。"),
                        ("I decided to〜", "日常", "I decided to stay home today.", "今日は家にいることに決めました。"),
                        ("I decided to〜", "日常", "I decided to go shopping.", "買い物に行くことに決めました。"),
                        ("I decided to〜", "仕事", "I decided to change jobs.", "転職することに決めました。"),
                        ("I decided to〜", "仕事", "I decided to start my own business.", "起業することに決めました。"),
                        ("I decided to〜", "仕事", "I decided to talk to my boss.", "上司に話すことに決めました。"),
                        ("I decided to〜", "仕事", "I decided to apply for the position.", "その職に応募することに決めました。"),
                        ("I decided to〜", "仕事", "I decided to work from home.", "在宅勤務することに決めました。"),
                        ("I decided to〜", "勉強", "I decided to study English every day.", "毎日英語を勉強することに決めました。"),
                        ("I decided to〜", "勉強", "I decided to take an online course.", "オンライン講座を受けることに決めました。"),
                        ("I decided to〜", "勉強", "I decided to learn programming.", "プログラミングを学ぶことに決めました。"),
                        ("I decided to〜", "勉強", "I decided to read more books.", "もっと本を読むことに決めました。"),
                        ("I decided to〜", "勉強", "I decided to keep a study journal.", "学習ノートをつけることに決めました。"),
                        ("I decided to〜", "健康", "I decided to eat healthier.", "もっと健康的に食べることに決めました。"),
                        ("I decided to〜", "健康", "I decided to exercise regularly.", "定期的に運動することに決めました。"),
                        ("I decided to〜", "健康", "I decided to drink more water.", "もっと水を飲むことに決めました。"),
                        ("I decided to〜", "健康", "I decided to go on a diet.", "ダイエットをすることに決めました。"),
                        ("I decided to〜", "健康", "I decided to walk every morning.", "毎朝歩くことに決めました。"),
                        ("I decided to〜", "その他", "I decided to travel alone.", "一人旅をすることに決めました。"),
                        ("I decided to〜", "その他", "I decided to move to another city.", "別の街に引っ越すことに決めました。"),
                        ("I decided to〜", "その他", "I decided to visit my parents.", "両親に会いに行くことに決めました。"),
                        ("I decided to〜", "その他", "I decided to adopt a pet.", "ペットを飼うことに決めました。"),
                        ("I decided to〜", "その他", "I decided to learn photography.", "写真を学ぶことに決めました。"),
                        
        // MARK: - Who ~
                        ("Who", "代表例", "Who are you?", "あなたは誰ですか？"),
                        ("Who", "代表例", "Who is your boss?", "あなたの上司は誰ですか？"),
                        ("Who", "代表例", "Who is going with you?", "誰が一緒に行きますか？"),
                        ("Who", "代表例", "Who took this picture?", "この写真は誰が撮ったの？"),
                        ("Who", "代表例", "Who is the oldest in your family?", "家族で一番年上は誰ですか？"),
                        ("Who", "代表例", "Who invited you?", "誰があなたを招待したの？"),
                        ("Who", "代表例", "Who is your favorite teacher?", "一番好きな先生は誰？"),
                        ("Who", "代表例", "Who do you live with?", "誰と一緒に住んでるの？"),
                        
        // MARK: - What ~
                        ("What", "代表例", "What are you doing?", "今何してるの？"),
                        ("What", "代表例", "What do you want to eat?", "何食べたい？"),
                        ("What", "代表例", "What do you like to do?", "何をするのが好き？"),
                        ("What", "代表例", "What should I do?", "何をすればいい？"),
                        ("What", "代表例", "What’s your favorite movie?", "お気に入りの映画は？"),
                        ("What", "代表例", "What time is it?", "今何時？"),
                        ("What", "代表例", "What’s wrong?", "どうしたの？"),
                        ("What", "代表例", "What’s the weather like today?", "今日の天気は？"),
                        ("What", "代表例", "What happened?", "何があったの？"),
                        ("What", "代表例", "What did you buy?", "何を買ったの？"),
                    
                        
        // MARK: - When ~
                        ("When", "代表例", "When is your birthday?", "誕生日はいつ？"),
                        ("When", "代表例", "When do you usually get up?", "普段何時に起きる？"),
                        ("When", "代表例", "When is the event?", "イベントはいつ？"),
                        ("When", "代表例", "When are we leaving?", "いつ出発するの？"),
                        ("When", "代表例", "When did you start studying English?", "英語の勉強いつ始めた？"),
                        ("When", "代表例", "When did you get home last night?", "昨日いつ帰ったの？"),
                        ("When", "代表例", "When can we meet?", "いつ会える？"),
                        ("When", "代表例", "When do you go to work?", "いつ仕事に行くの？"),
                        ("When", "代表例", "When will you come back?", "いつ戻ってくる？"),
                        ("When", "代表例", "When should I call you?", "いつ電話すればいい？"),
                        
        // MARK: - When ~
                        ("Where", "代表例", "Where are you now?", "今どこにいるの？"),
                        ("Where", "代表例", "Where are you going?", "どこに行くの？"),
                        ("Where", "代表例", "Where did you buy that?", "それどこで買ったの？"),
                        ("Where", "代表例", "Where is the nearest station?", "一番近い駅はどこ？"),
                        ("Where", "代表例", "Where do you live?", "どこに住んでるの？"),
                        ("Where", "代表例", "Where is my phone?", "私の携帯どこ？"),
                        ("Where", "代表例", "Where were you last night?", "昨日の夜どこにいたの？"),
                        ("Where", "代表例", "Where should we meet?", "どこで会う？"),
                        ("Where", "代表例", "Where did you go to school?", "どこで学校に通ってた？"),
                        ("Where", "代表例", "Where do you want to eat?", "どこで食べたい？"),
                        
        // MARK: - Why ~
                        ("Why", "代表例", "Why are you late?", "なんで遅れたの？"),
                        ("Why", "代表例", "Why are you so upset?", "なんでそんなに怒ってるの？"),
                        ("Why", "代表例", "Why did you choose that?", "なんでそれを選んだの？"),
                        ("Why", "代表例", "Why don’t we go together?", "一緒に行かない？"),
                        ("Why", "代表例", "Why did you quit your job?", "なんで仕事を辞めたの？"),
                        ("Why", "代表例", "Why do you like it?", "なんでそれが好きなの？"),
                        
        // MARK: - How ~
                        ("How", "代表例", "How do you go to work?", "どうやって通勤してるの？"),
                        ("How", "代表例", "How do you cook this?", "これどうやって作るの？"),
                        ("How", "代表例", "How are you feeling?", "気分はどう？"),
                        ("How", "代表例", "How long does it take?", "どのくらい時間かかる？"),
                        ("How", "代表例", "How often do you exercise?", "どのくらいの頻度で運動する？"),
                        ("How", "代表例", "How much is this?", "これはいくら？"),


        ]
        // ✅ ここでインデックス順に時刻をずらして保存（= 登録順を createdAt に刻む）
        _ = Date()
        for (tag, cat, en, ja) in samples {
            let e = PhraseEntity(en: en, ja: ja, tag: tag, category: cat)
            context.insert(e)
        }
        try? context.save()
    }
}

